### ISSUE TITLE
2538 JOIN problem when routers are on the way

### ISSUE THREAD

**Issue by Hacker-CB** [jethome-ru/zigbee-firmware#2]
In most cases it is impossible to join new devices if some routers are on the way.

**Comment by Hacker-CB** [comment]
Fixed.

**Comment by LeoDJ** [comment]
A question, because I don't understand the repository structure very well:
Can I use the `JH_2538_2592_ZNP_USB_20201010.hex` file for a Modkamru USB stick, or do I need to use `MODKAMRU_V3/MODKAMRU_V3_USB.hex`?

Because the latter one doesn't have this fix implemented and I noticed that I can't pair devices that are far away and only connected via routers.

Also: can I update the firmware of the coordinator without having to re-pair all my devices?

**Comment by Hacker-CB** [comment]
You should use `JH_2538_2592_ZNP_USB_20201010.hex` fir modkamru stick. `MODKAMRU_V3/MODKAMRU_V3_USB.hex` is old one.

It is possible to update firmware without repairing if you will follow steps described here: https://github.com/jethome-ru/zigbee-firmware/blob/master/ti/coordinator/cc2538_cc2592/README.md

**Comment by LeoDJ** [comment]
Yes, that worked without a problem. Thank you very much!

**Comment by Hacker-CB** [comment]
No, just download and flash firmware from the latest `.zip` file (usb or uart, depending on your hardware type)
