### ISSUE TITLE
Router firmware for CC2538 won't work

### ISSUE THREAD

**Issue by wes1993** [jethome-ru/zigbee-firmware#3]
Hello,
I'm trying to flash the router firmware in my CC2538 stick (Modkam.ru) But with version 19052020 the blue led still fixed blu and do nothig, WIthe the 20 and 22 version the stick remain off no led or other else :-(
Do you have some suggestion?
Thanks a lot
Stefano

**Comment by Hacker-CB** [comment]
Which way are you using to flash? SBL(Uart)?
Please note, it is possible to flash via UART **only** if SBL was enabled in previous firmware

**Comment by wes1993** [comment]
Thanks a lot for your fast reply and for the FW :-)
I’m not so expert, I’m using j-link flasher, select erase chip - check blank - program and verify.
I select Jtag and 4000

**Comment by Hacker-CB** [comment]
Latest router firmware is `jh_2538_router_20200522.hex`.
Accroding doc from https://github.com/jethome-ru/zigbee-firmware/tree/master/ti/router/cc2538_cc2592:

Blue light - Constant glow - a device on the network

So, seems that your router already joined your network.

You can try to reset:

Holding down the FLASH button for more than 5 seconds resets the device to factory settings and a software RESET is performed. Since a low level at FLASH (PA7) is a condition for entering Bootloader mode after RESET, a quick blinking LED1 (frequency 5Hz) indicates that the condition for reset is met, but you must release it to continue button;

**Comment by wes1993** [comment]
My stick only with FW 19 won’t blink :(
Just fixed blue light and if I press the button do nothing... 
with the other firmware is dead completely

**Comment by wes1993** [comment]
![Uploading 404993A2-26B8-478E-B7F8-44FD6701F260.jpeg…]()

**Comment by wes1993** [comment]
![BCECA3E6-D920-44C5-A050-D527A6EDC68F](https://user-images.githubusercontent.com/52070589/96451181-7ddb3d80-1217-11eb-84fd-a980b6a2add5.jpeg)

**Comment by Hacker-CB** [comment]
Sorry, I have no idea.
I have same stick and it works.

**Comment by wes1993** [comment]
Thanks for your help :)
It’s strange :(
